### PR TITLE
Mig 14 account bank statement import camt oca

### PR DESCRIPTION
**Pull request by aPoluden**
Please review migration commit [396a223](https://github.com/versada/bank-statement-import/pull/2/commits/396a22374a6d207ffe10a18319a78d5259ce229b)

### CODE REVIEW

**Comment by psugne** [comment]
@aPoluden maybe it's possible to do a [PR](https://github.com/OCA/bank-statement-import) on OCA too following OCA
[maintainer-tools](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0)?

**Comment by naglis** [comment]
Was it not already ported (https://github.com/OCA/bank-statement-import/pull/369) and renamed in the process (see https://github.com/OCA/bank-statement-import/pull/369/commits/4c7afd42faf458d20bd60d686698b2292d4f7fd9)?

**Comment by aPoluden** [comment]
> Was it not already ported ([OCA#369](https://github.com/OCA/bank-statement-import/pull/369)) and renamed in the process (see [OCA@4c7afd4](https://github.com/OCA/bank-statement-import/commit/4c7afd42faf458d20bd60d686698b2292d4f7fd9))?

@naglis did you know about it? Or do you check the V14 module by name? Or checked PR by title?

**Comment by psugne** [comment]
Seems somebody forgot to update [migration](https://github.com/OCA/bank-statement-import/issues/341) file.

**Comment by naglis** [comment]
> > Was it not already ported ([OCA#369](https://github.com/OCA/bank-statement-import/pull/369)) and renamed in the process (see [OCA@4c7afd4](https://github.com/OCA/bank-statement-import/commit/4c7afd42faf458d20bd60d686698b2292d4f7fd9))?
> 
> @naglis did you know about it? Or do you check the V14 module by name? Or checked PR by title?

I checked the [migration issue](https://github.com/OCA/bank-statement-import/issues/341), saw a rename was implied, so I checked the renamed addon (`account_statement_import_camt`).

**Pull request closed without merging**
